name="Chansey"
dextext="A rare and elusive POKeMON that is said to bring happiness to those who manage to get it."
type1="normal"
type2=""
height="3ft 7in (1.09m)"
weight="76.3 lbs (34.6 kg)"
kind="Egg Pokemon"