name="Growlithe"
dextext="Very protective of its territory. It will bark and bite to repel intruders from its space."
type1="fire"
type2=""
height="2ft 4in (0.71m)"
weight="41.9 lbs (19.0 kg)"
kind="Puppy Pokemon"