name="Ninetales"
dextext="Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse."
type1="fire"
type2=""
height="3ft 7in (1.09m)"
weight="43.9 lbs (19.9 kg)"
kind="Fox Pokemon"