name="Pinsir"
dextext="If it fails to crush the victim in its pincers, it will swing it around and toss it hard."
type1="bug"
type2="flying"
height="4ft 11in (1.50m)"
weight="121.3 lbs (55.0 kg)"
kind="Stag Beetle Pokemon"