name="Diglett"
dextext="Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground."
type1="ground"
type2=""
height="0ft 8in (0.20m)"
weight="1.8 lbs (0.8 kg)"
kind="Mole Pokemon"