name="Mewtwo"
dextext="It was created by a scientist after years of horrific gene splicing and DNA engineering experiments."
type1="psychic"
type2="fighting"
height="6ft 7in (2.01m)"
weight="269 lbs (122.0 kg)"
kind="Genetic Pokemon"