name="Tentacool"
dextext="Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid."
type1="water"
type2="poison"
height="2ft 11in (0.89m)"
weight="100.3 lbs (45.5 kg)"
kind="Jellyfish Pokemon"