name="Jigglypuff"
dextext="When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."
type1="normal"
type2="fairy"
height="1ft 8in (0.51m)"
weight="12.1 lbs (5.5 kg)"
kind="Balloon Pokemon"