name="Raichu"
dextext="Its long tail serves as a ground to protect itself from its own high voltage power."
type1="electric"
type2=""
height="2ft 7in (0.79m)"
weight="66.1 lbs (30.0 kg)"
kind="Mouse Pokemon"