name="Blastoise"
dextext="A brutal POKeMON with pressurized water jets on its shell. They are used for high speed tackles."
type1="water"
type2=""
height="5ft 3in (1.60m)"
weight="188.5 lbs (85.5 kg)"
kind="Shellfish Pokemon"