name="Machoke"
dextext="Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions."
type1="fighting"
type2=""
height="4ft 11in (1.50m)"
weight="155.4 lbs (70.5 kg)"
kind="Superpower Pokemon"