name="Onix"
dextext="As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."
type1="rock"
type2="ground"
height="28ft 10in (8.79m)"
weight="463 lbs (210.0 kg)"
kind="Rock Snake Pokemon"