name="Charmeleon"
dextext="When it swings its burning tail, it elevates the temperature to unbearably high levels."
type1="fire"
type2=""
height="3ft 7in (1.09m)"
weight="41.9 lbs (19.0 kg)"
kind="Flame Pokemon"