name="Marowak"
dextext="The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."
type1="ground"
type2=""
height="3ft 3in (0.99m)"
weight="99.2 lbs (45.0 kg)"
kind="Bone Keeper Pokemon"