name="Seaking"
dextext="In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks."
type1="water"
type2=""
height="4ft 3in (1.30m)"
weight="86 lbs (39.0 kg)"
kind="Goldfish Pokemon"