name="Mankey"
dextext="Extremely quick to anger. It could be docile one moment then thrashing away the next instant."
type1="fighting"
type2=""
height="1ft 8in (0.51m)"
weight="61.7 lbs (28.0 kg)"
kind="Pig Monkey Pokemon"