name="Nidoran♂ (m)"
dextext="Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."
type1="poison"
type2=""
height="1ft 8in (0.51m)"
weight="19.8 lbs (9.0 kg)"
kind="Poison Pin Pokemon"