name="Dewgong"
dextext="Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters."
type1="water"
type2="ice"
height="5ft 7in (1.70m)"
weight="264.6 lbs (120.0 kg)"
kind="Sea Lion Pokemon"