name="Bulbasaur"
dextext="A strange seed was planted on its back at birth. The plant sprouts and grows with this POKeMON."
type1="grass"
type2="poison"
height="2ft 4in (0.71m)"
weight="15.2 lbs (6.9 kg)"
kind="Seed Pokemon"