name="Wartortle"
dextext="Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance."
type1="water"
type2=""
height="3ft 3in (0.99m)"
weight="49.6 lbs (22.5 kg)"
kind="Turtle Pokemon"