name="Primeape"
dextext="Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught."
type1="fighting"
type2=""
height="3ft 3in (0.99m)"
weight="70.5 lbs (32.0 kg)"
kind="Pig Monkey Pokemon"