name="Jynx"
dextext="It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."
type1="ice"
type2="psychic"
height="4ft 7in (1.40m)"
weight="89.5 lbs (40.6 kg)"
kind="Human Shape Pokemon"