name="Sandshrew"
dextext="Burrows deep underground in arid locations far from water. It only emerges to hunt for food."
type1="ground"
type2=""
height="2ft 0in (0.61m)"
weight="26.5 lbs (12.0 kg)"
kind="Mouse Pokemon"