name="Mew"
dextext="So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."
type1="psychic"
type2=""
height="1ft 4in (0.41m)"
weight="8.8 lbs (4.0 kg)"
kind="New Species Pokemon"