name="Zapdos"
dextext="A legendary bird POKeMON that is said to appear from clouds while dropping enormous lightning bolts."
type1="electric"
type2="flying"
height="5ft 3in (1.60m)"
weight="116 lbs (52.6 kg)"
kind="Electric Pokemon"