name="Grimer"
dextext="Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories."
type1="poison"
type2=""
height="2ft 11in (0.89m)"
weight="66.1 lbs (30.0 kg)"
kind="Sludge Pokemon"