name="Gastly"
dextext="Almost invisible, this gaseous POKeMON cloaks the target and puts it to sleep without notice."
type1="ghost"
type2="poison"
height="4ft 3in (1.30m)"
weight="0.2 lbs (0.1 kg)"
kind="Gas Pokemon"