name="Weezing"
dextext="Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years."
type1="poison"
type2=""
height="3ft 11in (1.19m)"
weight="20.9 lbs (9.5 kg)"
kind="Poison Gas Pokemon"