name="Jolteon"
dextext="It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts."
type1="electric"
type2=""
height="2ft 7in (0.79m)"
weight="54 lbs (24.5 kg)"
kind="Lightning Pokemon"