name="Snorlax"
dextext="Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."
type1="normal"
type2=""
height="6ft 11in (2.11m)"
weight="1014.1 lbs (460.0 kg)"
kind="Sleeping Pokemon"