name="Venonat"
dextext="Lives in the shadows of tall trees where it eats insects. It is attracted by light at night."
type1="bug"
type2="poison"
height="3ft 3in (0.99m)"
weight="66.1 lbs (30.0 kg)"
kind="Insect Pokemon"