name="Nidoqueen"
dextext="Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves."
type1="poison"
type2="ground"
height="4ft 3in (1.30m)"
weight="132.3 lbs (60.0 kg)"
kind="Drill Pokemon"