name="Sandslash"
dextext="Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape."
type1="ground"
type2=""
height="3ft 3in (0.99m)"
weight="65 lbs (29.5 kg)"
kind="Mouse Pokemon"