name="Hitmonlee"
dextext="When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."
type1="fighting"
type2=""
height="4ft 11in (1.50m)"
weight="109.8 lbs (49.8 kg)"
kind="Kicking Pokemon"