name="Bellsprout"
dextext="A carnivorous POKeMON that traps and eats bugs. It uses its root feet to soak up needed moisture."
type1="grass"
type2="poison"
height="2ft 4in (0.71m)"
weight="8.8 lbs (4.0 kg)"
kind="Flower Pokemon"