name="Exeggutor"
dextext="Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE."
type1="grass"
type2="psychic"
height="6ft 7in (2.01m)"
weight="264.6 lbs (120.0 kg)"
kind="Coconut Pokemon"