name="Eevee"
dextext="Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs."
type1="normal"
type2=""
height="1ft 0in (0.30m)"
weight="14.3 lbs (6.5 kg)"
kind="Evolution Pokemon"