name="Muk"
dextext="Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."
type1="poison"
type2=""
height="3ft 11in (1.19m)"
weight="66.1 lbs (30.0 kg)"
kind="Sludge Pokemon"