name="Poliwag"
dextext="Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand."
type1="water"
type2=""
height="2ft 0in (0.61m)"
weight="27.3 lbs (12.4 kg)"
kind="Tadpole Pokemon"