name="Arbok"
dextext="It is rumored that the ferocious warning markings on its belly differ from area to area."
type1="poison"
type2=""
height="11ft 6in (3.51m)"
weight="143.3 lbs (65.0 kg)"
kind="Cobra Pokemon"