name="Graveler"
dextext="Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."
type1="rock"
type2="ground"
height="3ft 3in (0.99m)"
weight="231.5 lbs (105.0 kg)"
kind="Rock Pokemon"